### ISSUE TITLE
Open league crash

### ISSUE THREAD

**Issue by nknm** [Ja-Sa-La/League-Account-Manager#6]
"open league" button crashes the client for me

**Comment by Ja-Sa-La** [comment]
Hi, please download the latest version and give me the error log  @nknm

**Comment by nknm** [comment]
Now it does not open for me

2024-03-06 19:57:24.6996|ERROR|League_Account_Manager.views.Page1|Error loading data|System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Match(String input)
   at League_Account_Manager.views.Page1.loaddata()

settings are
{"filename":"List","updates":true}

**Comment by Ja-Sa-La** [comment]
is your league of legends and riot games folders somewhere else than 
"C:\Riot Games"

**Comment by nknm** [comment]
oh, its not on that path no

**Comment by Ja-Sa-La** [comment]
i see, i'll add ability to manually set the location of the folder

**Comment by nknm** [comment]
cheers boss, I even forgot i had it on my other drive tbh, its been there for years

**Comment by nknm** [comment]
Will do tomorrow, first thing

**Comment by nknm** [comment]
all good now, Login doesnt work but Login V2 works like a charm
